name: CI

on:
  push:
    branches: [main, ci-actions]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Test install
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo apt install ubuntu-desktop-minimal
          dbus-run-session make install
